#!/usr/bin/env python3
"""Generate stable Chapter 5 baseline figures from PX4-vs-GT CSV logs."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REQUIRED_COLUMNS = {
    "timestamp",
    "px4_pos_x",
    "px4_pos_y",
    "px4_pos_z",
    "gazebo_pos_x",
    "gazebo_pos_y",
    "gazebo_pos_z",
    "pos_error_norm",
    "vel_error_norm",
    "error_yaw",
    "attitude_error_norm",
}


def parse_cli() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, required=True, help="CSV generated by record_px4_baseline.py")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=repo_root / "paper_outputs" / "ch5",
        help="Directory for generated figures and tables.",
    )
    parser.add_argument(
        "--scenario-label",
        type=str,
        default="PX4 baseline",
        help="Label stored in the generated statistics table.",
    )
    return parser.parse_args()


def setup_style() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": 160,
            "savefig.dpi": 220,
            "font.size": 10,
            "axes.titlesize": 12,
            "axes.labelsize": 10,
            "legend.fontsize": 9,
            "axes.grid": True,
            "grid.alpha": 0.25,
        }
    )


def ensure_columns(df: pd.DataFrame) -> None:
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        missing_list = ", ".join(sorted(missing))
        raise ValueError(f"Missing required CSV columns: {missing_list}")
    if df.empty:
        raise ValueError("CSV contains headers only; no recorded samples were written.")
    if df[["gazebo_pos_x", "gazebo_pos_y", "gazebo_pos_z"]].isna().all().all():
        raise ValueError("CSV does not contain any ground-truth position samples.")


def dataframe_to_markdown(df: pd.DataFrame) -> str:
    columns = list(df.columns)
    rows = [columns] + [[str(row[col]) for col in columns] for _, row in df.iterrows()]
    widths = [max(len(str(row[i])) for row in rows) for i in range(len(columns))]

    def fmt_row(row: list[str]) -> str:
        return "| " + " | ".join(str(cell).ljust(widths[i]) for i, cell in enumerate(row)) + " |"

    sep = "| " + " | ".join("-" * widths[i] for i in range(len(columns))) + " |"
    lines = [fmt_row(columns), sep]
    for _, row in df.iterrows():
        lines.append(fmt_row([str(row[col]) for col in columns]))
    return "\n".join(lines) + "\n"


def make_trajectory_figure(df: pd.DataFrame, output_dir: Path) -> Path:
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.0), constrained_layout=True)

    axes[0].plot(df["gazebo_pos_x"], df["gazebo_pos_y"], label="Gazebo GT", lw=2.2, color="#0f766e")
    axes[0].plot(df["px4_pos_x"], df["px4_pos_y"], label="PX4", lw=1.8, color="#1d4ed8")
    axes[0].scatter(df["gazebo_pos_x"].iloc[0], df["gazebo_pos_y"].iloc[0], color="#059669", s=45, zorder=3)
    axes[0].scatter(df["gazebo_pos_x"].iloc[-1], df["gazebo_pos_y"].iloc[-1], color="#b91c1c", s=45, zorder=3)
    axes[0].set_title("Top-down trajectory comparison")
    axes[0].set_xlabel("x / m")
    axes[0].set_ylabel("y / m")
    axes[0].axis("equal")
    axes[0].legend(loc="best")

    axes[1].plot(df["timestamp"], df["gazebo_pos_z"], label="Gazebo GT", lw=2.2, color="#0f766e")
    axes[1].plot(df["timestamp"], df["px4_pos_z"], label="PX4", lw=1.8, color="#1d4ed8")
    axes[1].set_title("Altitude versus time")
    axes[1].set_xlabel("time / s")
    axes[1].set_ylabel("z / m")
    axes[1].legend(loc="best")

    fig.suptitle("Figure 5-4  PX4 baseline trajectory against Gazebo ground truth", fontsize=13, weight="bold")
    output = output_dir / "fig5_4_px4_vs_gt_trajectory.png"
    fig.savefig(output, bbox_inches="tight")
    plt.close(fig)
    return output


def make_error_figure(df: pd.DataFrame, output_dir: Path) -> Path:
    fig, axes = plt.subplots(3, 1, figsize=(11.2, 8.4), sharex=True, constrained_layout=True)
    t = df["timestamp"].to_numpy()

    axes[0].plot(t, df["pos_error_norm"], color="#1d4ed8", lw=1.8)
    axes[0].set_ylabel("position / m")
    axes[0].set_title("Position error norm")

    axes[1].plot(t, df["vel_error_norm"], color="#7c3aed", lw=1.8)
    axes[1].set_ylabel("velocity / m/s")
    axes[1].set_title("Velocity error norm")

    axes[2].plot(t, df["error_yaw"], color="#ea580c", lw=1.8)
    axes[2].set_ylabel("yaw / deg")
    axes[2].set_xlabel("time / s")
    axes[2].set_title("Yaw error")

    fig.suptitle("Figure 5-7  PX4 baseline error time series", fontsize=13, weight="bold")
    output = output_dir / "fig5_7_px4_error_timeseries.png"
    fig.savefig(output, bbox_inches="tight")
    plt.close(fig)
    return output


def write_stats_table(df: pd.DataFrame, scenario_label: str, output_dir: Path) -> None:
    stats = pd.DataFrame(
        [
            {
                "场景标签": scenario_label,
                "样本数": int(len(df)),
                "时长(s)": round(float(df["timestamp"].iloc[-1] - df["timestamp"].iloc[0]), 3),
                "位置RMSE(m)": round(float(np.sqrt(np.mean(np.square(df["pos_error_norm"])))), 4),
                "速度RMSE(m/s)": round(float(np.sqrt(np.mean(np.square(df["vel_error_norm"])))), 4),
                "航向误差RMS(deg)": round(float(np.sqrt(np.mean(np.square(df["error_yaw"])))), 4),
                "姿态误差RMS(deg)": round(float(np.sqrt(np.mean(np.square(df["attitude_error_norm"])))), 4),
                "最大漂移(m)": round(float(df["pos_error_norm"].max()), 4),
            }
        ]
    )

    csv_path = output_dir / "table5_4_px4_baseline_stats.csv"
    md_path = output_dir / "table5_4_px4_baseline_stats.md"
    stats.to_csv(csv_path, index=False, encoding="utf-8-sig")
    md_path.write_text(dataframe_to_markdown(stats), encoding="utf-8")
    print(f"generated: {csv_path}")
    print(f"generated: {md_path}")


def main() -> int:
    args = parse_cli()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    setup_style()

    df = pd.read_csv(args.csv)
    ensure_columns(df)
    df = df.sort_values("timestamp").reset_index(drop=True)

    outputs = [
        make_trajectory_figure(df, args.output_dir),
        make_error_figure(df, args.output_dir),
    ]
    for output in outputs:
        print(f"generated: {output}")
    write_stats_table(df, args.scenario_label, args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
