#!/usr/bin/env bash

set -euo pipefail

CMD="${1:-}"
RUN_REF="${2:-manual_mainline_15_postflight_idle}"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WS_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
BRINGUP_SCRIPT="${SCRIPT_DIR}/px4_interactive_safe_bringup.sh"
DEFAULT_RUN_NAME="manual_mainline_15_postflight_idle"

usage() {
  cat <<EOF
usage: $(basename "$0") {start|status|stop|summary|show-env} [run_name|/abs/run_dir]

Defaults:
  run_name: ${DEFAULT_RUN_NAME}
  run_dir:  ${WS_ROOT}/artifacts/manual/${DEFAULT_RUN_NAME}
EOF
}

resolve_run_dir() {
  local run_ref="${1:-${DEFAULT_RUN_NAME}}"

  if [[ -z "${run_ref}" ]]; then
    run_ref="${DEFAULT_RUN_NAME}"
  fi

  if [[ "${run_ref}" == /* ]]; then
    printf '%s\n' "${run_ref}"
  else
    printf '%s\n' "${WS_ROOT}/artifacts/manual/${run_ref}"
  fi
}

csv_rows() {
  local path="$1"

  if [[ ! -s "${path}" ]]; then
    printf '0\n'
    return
  fi

  local total_lines
  total_lines="$(wc -l < "${path}")"
  if (( total_lines > 0 )); then
    printf '%s\n' "$((total_lines - 1))"
  else
    printf '0\n'
  fi
}

show_env() {
  cat <<EOF
RUN_DIR=${RUN_DIR}
ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
PX4_SAFE_PX4_WORLD=${PX4_SAFE_PX4_WORLD}
PX4_SAFE_START_MAVROS=${PX4_SAFE_START_MAVROS}
PX4_SAFE_START_QGC=${PX4_SAFE_START_QGC}
PX4_SAFE_START_MONITOR=${PX4_SAFE_START_MONITOR}
PX4_SAFE_START_COMPARE=${PX4_SAFE_START_COMPARE}
PX4_SAFE_START_GPS_PROBES=${PX4_SAFE_START_GPS_PROBES}
PX4_SAFE_START_PLOTJUGGLER=${PX4_SAFE_START_PLOTJUGGLER}
PX4_SAFE_HEADLESS=${PX4_SAFE_HEADLESS}
PX4_SAFE_NO_PXH=${PX4_SAFE_NO_PXH}
PX4_SAFE_MAVROS_PROFILE=${PX4_SAFE_MAVROS_PROFILE}
PX4_SAFE_GCS_LINK_PROFILE=${PX4_SAFE_GCS_LINK_PROFILE}
PX4_SAFE_GCS_RATE_BPS=${PX4_SAFE_GCS_RATE_BPS}
PX4_SAFE_GCS_POSITION_RATE_HZ=${PX4_SAFE_GCS_POSITION_RATE_HZ}
PX4_SAFE_GCS_ATTITUDE_RATE_HZ=${PX4_SAFE_GCS_ATTITUDE_RATE_HZ}
PX4_SAFE_GCS_TARGET_RATE_HZ=${PX4_SAFE_GCS_TARGET_RATE_HZ}
PX4_SAFE_GCS_SERVO_RATE_HZ=${PX4_SAFE_GCS_SERVO_RATE_HZ}
PX4_SAFE_GCS_RC_RATE_HZ=${PX4_SAFE_GCS_RC_RATE_HZ}
PX4_SAFE_GCS_FLOW_RATE_HZ=${PX4_SAFE_GCS_FLOW_RATE_HZ}
PX4_SAFE_COMPARE_KF_GINS_PARAM_FILE=${PX4_SAFE_COMPARE_KF_GINS_PARAM_FILE}
PX4_SAFE_COMPARE_KF_GINS_CORE_CONFIG_FILE=${PX4_SAFE_COMPARE_KF_GINS_CORE_CONFIG_FILE}
PX4_SAFE_COMPARE_FORCE_ZERO_ANTLEVER=${PX4_SAFE_COMPARE_FORCE_ZERO_ANTLEVER}
PX4_SAFE_COMPARE_ENABLE_REAL_TIME=${PX4_SAFE_COMPARE_ENABLE_REAL_TIME}
PX4_SAFE_COMPARE_CSV_PATH=${PX4_SAFE_COMPARE_CSV_PATH}
PX4_SAFE_COMPARE_IEKF_RAW_TOPIC=${PX4_SAFE_COMPARE_IEKF_RAW_TOPIC}
PX4_SAFE_COMPARE_COMPUTE_RAW_METRICS=${PX4_SAFE_COMPARE_COMPUTE_RAW_METRICS}
PX4_SAFE_COMPARE_RAW_CALLBACK_MODE=${PX4_SAFE_COMPARE_RAW_CALLBACK_MODE}
PX4_SAFE_COMPARE_GNSS_UPDATE_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_GNSS_UPDATE_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_MAX_RATE_HZ=${PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_MAX_RATE_HZ}
PX4_SAFE_COMPARE_ENABLE_RQ_SHADOW=${PX4_SAFE_COMPARE_ENABLE_RQ_SHADOW}
PX4_SAFE_COMPARE_RQ_SHADOW_NAMESPACE=${PX4_SAFE_COMPARE_RQ_SHADOW_NAMESPACE}
PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_PARAM_FILE=${PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_PARAM_FILE}
PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_CORE_CONFIG_FILE=${PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_CORE_CONFIG_FILE}
PX4_SAFE_COMPARE_RQ_SHADOW_STATE_UPDATE_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_RQ_SHADOW_STATE_UPDATE_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_CSV_PATH=${PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_CSV_PATH}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_HEADING_UPDATE_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_HEADING_UPDATE_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_STATE_PUBLISH_DEBUG_CSV_PATH=${PX4_SAFE_COMPARE_STATE_PUBLISH_DEBUG_CSV_PATH}
PX4_SAFE_COMPARE_PUBLISH_STATE_AFTER_GNSS_UPDATE=${PX4_SAFE_COMPARE_PUBLISH_STATE_AFTER_GNSS_UPDATE}
PX4_SAFE_COMPARE_PUBLISH_PX4_SPHERE_PROJECTION=${PX4_SAFE_COMPARE_PUBLISH_PX4_SPHERE_PROJECTION}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ENABLE=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ENABLE}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_MISSION=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_MISSION}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_RTL=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_RTL}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_OTHER=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_OTHER}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ALPHA=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ALPHA}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_DEEP_THRESHOLD_MPS2=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_DEEP_THRESHOLD_MPS2}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_FRAC_THRESHOLD=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_FRAC_THRESHOLD}
PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_HISTORY_START_SEC=${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_HISTORY_START_SEC}
PX4_SAFE_COMPARE_PUBLISH_STAMP_MODE=${PX4_SAFE_COMPARE_PUBLISH_STAMP_MODE}
PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_FUTURE_SEC=${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_FUTURE_SEC}
PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_PAST_SEC=${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_PAST_SEC}
PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_OFFSET_BIAS_SEC=${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_OFFSET_BIAS_SEC}
PX4_SAFE_COMPARE_RAW_ODOM_DECIMATION=${PX4_SAFE_COMPARE_RAW_ODOM_DECIMATION}
PX4_SAFE_COMPARE_PATH_PUBLISH_RATE_HZ=${PX4_SAFE_COMPARE_PATH_PUBLISH_RATE_HZ}
PX4_SAFE_COMPARE_POSE_DECIMATION=${PX4_SAFE_COMPARE_POSE_DECIMATION}
PX4_SAFE_COMPARE_MAX_PATH_POINTS=${PX4_SAFE_COMPARE_MAX_PATH_POINTS}
PX4_SAFE_COMPARE_CORE_PROCESSING_ENABLE=${PX4_SAFE_COMPARE_CORE_PROCESSING_ENABLE}
PX4_SAFE_COMPARE_CORE_IMU_DECIMATION=${PX4_SAFE_COMPARE_CORE_IMU_DECIMATION}
PX4_SAFE_COMPARE_CORE_MAX_IMU_RATE_HZ=${PX4_SAFE_COMPARE_CORE_MAX_IMU_RATE_HZ}
PX4_SAFE_COMPARE_EKF2_USE_INPUT_STAMP=${PX4_SAFE_COMPARE_EKF2_USE_INPUT_STAMP}
PX4_SAFE_COMPARE_GNSS_RELAY_MODE=${PX4_SAFE_COMPARE_GNSS_RELAY_MODE}
PX4_SAFE_COMPARE_ENABLE_GNSS_RELAY=${PX4_SAFE_COMPARE_ENABLE_GNSS_RELAY}
PX4_SAFE_COMPARE_GNSS_RELAY_SUBSCRIBE_ENABLE=${PX4_SAFE_COMPARE_GNSS_RELAY_SUBSCRIBE_ENABLE}
PX4_SAFE_COMPARE_GNSS_RELAY_PUBLISH_ENABLE=${PX4_SAFE_COMPARE_GNSS_RELAY_PUBLISH_ENABLE}
PX4_SAFE_COMPARE_ENABLE_GPS_DROPZONES=${PX4_SAFE_COMPARE_ENABLE_GPS_DROPZONES}
PX4_SAFE_COMPARE_INJECT_DROPZONE_GPS_TO_PX4=${PX4_SAFE_COMPARE_INJECT_DROPZONE_GPS_TO_PX4}
PX4_SAFE_COMPARE_PX4_GPS_INJECTION_MODE=${PX4_SAFE_COMPARE_PX4_GPS_INJECTION_MODE}
PX4_SAFE_COMPARE_PX4_SET_PARAMS=${PX4_SAFE_COMPARE_PX4_SET_PARAMS}
PX4_SAFE_COMPARE_ENABLE_EKF2_RELAY=${PX4_SAFE_COMPARE_ENABLE_EKF2_RELAY}
PX4_SAFE_COMPARE_ENABLE_KF_GINS=${PX4_SAFE_COMPARE_ENABLE_KF_GINS}
PX4_SAFE_COMPARE_ENABLE_STATIC_TF=${PX4_SAFE_COMPARE_ENABLE_STATIC_TF}
PX4_SAFE_COMPARE_USE_SIM_GNSS_STD=${PX4_SAFE_COMPARE_USE_SIM_GNSS_STD}
PX4_SAFE_COMPARE_SIM_GNSS_STD_H_M=${PX4_SAFE_COMPARE_SIM_GNSS_STD_H_M}
PX4_SAFE_COMPARE_SIM_GNSS_STD_U_M=${PX4_SAFE_COMPARE_SIM_GNSS_STD_U_M}
PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_ENABLE=${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_ENABLE}
PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_SEC=${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_SEC}
PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MAX_SEC=${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MAX_SEC}
PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MIN_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MIN_SPEED_MPS}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_ENABLE=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_ENABLE}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_MISSION=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_MISSION}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_RTL=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_RTL}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_OTHER=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_OTHER}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_H_M=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_H_M}
PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_U_M=${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_U_M}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_ENABLE=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_ENABLE}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_MISSION=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_MISSION}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_RTL=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_RTL}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_START_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_START_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_FULL_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_FULL_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MIN_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MIN_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MAX_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MAX_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_ENABLE=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_ENABLE}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_MISSION=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_MISSION}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_RTL=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_RTL}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_REQUIRE_ARMED_CRUISE=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_REQUIRE_ARMED_CRUISE}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_TURNING=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_TURNING}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_POST_TURN=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_POST_TURN}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_START_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_START_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_FULL_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_FULL_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_START=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_START}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_FULL=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_FULL}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_LOW=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_LOW}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_HIGH=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_HIGH}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MIN_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MIN_H_M}
PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MAX_H_M=${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MAX_H_M}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ENABLE=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ENABLE}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_MISSION=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_MISSION}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_RTL=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_RTL}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_START_DEG_S=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_START_DEG_S}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_FULL_DEG_S=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_FULL_DEG_S}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ARW_Q_SCALE_MAX=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ARW_Q_SCALE_MAX}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_VRW_Q_SCALE_MAX=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_VRW_Q_SCALE_MAX}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRBIAS_Q_SCALE_MAX=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRBIAS_Q_SCALE_MAX}
PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ACCBIAS_Q_SCALE_MAX=${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ACCBIAS_Q_SCALE_MAX}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ENABLE=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ENABLE}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_NOISE_SCALE=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_NOISE_SCALE}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_MISSION=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_MISSION}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_RTL=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_RTL}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_TRIGGER_MPS2=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_TRIGGER_MPS2}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_FULL_MPS2=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_FULL_MPS2}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ARW_Q_SCALE_MAX=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ARW_Q_SCALE_MAX}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_VRW_Q_SCALE_MAX=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_VRW_Q_SCALE_MAX}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_GYRBIAS_Q_SCALE_MAX=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_GYRBIAS_Q_SCALE_MAX}
PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ACCBIAS_Q_SCALE_MAX=${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ACCBIAS_Q_SCALE_MAX}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_ENABLE=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_ENABLE}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_MISSION=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_MISSION}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_RTL=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_RTL}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_CORE_GNSS_DIFF_H_M=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_CORE_GNSS_DIFF_H_M}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_START_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_START_MPS}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_FULL_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_FULL_MPS}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_HOLD_UPDATES=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_HOLD_UPDATES}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MIN_H_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MIN_H_MPS}
PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MAX_H_MPS=${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MAX_H_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_ENABLE=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_ENABLE}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_MISSION=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_MISSION}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_RTL=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_RTL}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_TURNING=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_TURNING}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_POST_TURN=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_POST_TURN}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_CORE_GNSS_DIFF_H_M=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_CORE_GNSS_DIFF_H_M}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_START_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_START_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_FULL_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_FULL_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_START_H_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_START_H_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_FULL_H_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_FULL_H_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MIN_H_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MIN_H_MPS}
PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MAX_H_MPS=${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MAX_H_MPS}
PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_ENABLE=${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_ENABLE}
PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RESIDUAL_THRESHOLD_H_M=${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RESIDUAL_THRESHOLD_H_M}
PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_DX_OVER_RESIDUAL_THRESHOLD=${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_DX_OVER_RESIDUAL_THRESHOLD}
PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RECENT_TURNPOST_HOLD_SEC=${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RECENT_TURNPOST_HOLD_SEC}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ENABLE=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ENABLE}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_MISSION=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_MISSION}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_RTL=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_RTL}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TRIGGER_SOURCE=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TRIGGER_SOURCE}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MIN_H_M=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MIN_H_M}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_NOMINAL_H_M=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_NOMINAL_H_M}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MAX_H_M=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MAX_H_M}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_START_H_M=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_START_H_M}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_FULL_H_M=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_FULL_H_M}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_START_H_2D=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_START_H_2D}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_FULL_H_2D=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_FULL_H_2D}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_MAX_AGE_SEC=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_MAX_AGE_SEC}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ATTACK_SEC=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ATTACK_SEC}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_DECAY_SEC=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_DECAY_SEC}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ARMED_CRUISE_GAIN=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ARMED_CRUISE_GAIN}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TURN_GAIN=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TURN_GAIN}
PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_POST_TURN_GAIN=${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_POST_TURN_GAIN}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SUPERVISOR_ENABLE=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SUPERVISOR_ENABLE}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_MISSION=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_MISSION}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_RTL=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_RTL}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_START_H_2D=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_START_H_2D}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_FULL_H_2D=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_FULL_H_2D}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_START_H_M=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_START_H_M}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_FULL_H_M=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_FULL_H_M}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_START_H_M=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_START_H_M}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_FULL_H_M=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_FULL_H_M}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_START_DEG=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_START_DEG}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_FULL_DEG=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_FULL_DEG}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SCORE_TRIGGER=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SCORE_TRIGGER}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MAX_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MAX_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ENABLE=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ENABLE}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_MISSION=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_MISSION}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_RTL=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_RTL}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_START=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_START}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_FULL=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_FULL}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_START_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_START_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_FULL_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_FULL_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_LO_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_LO_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_HI_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_HI_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_LOW=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_LOW}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_HIGH=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_HIGH}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ATTACK_SEC=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ATTACK_SEC}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DECAY_SEC=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DECAY_SEC}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MIN_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MIN_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_NOMINAL_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_NOMINAL_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MAX_H_M=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MAX_H_M}
PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_OFFDIAG_CORR_LIMIT=${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_OFFDIAG_CORR_LIMIT}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_ENABLE=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_ENABLE}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_MISSION=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_MISSION}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_RTL=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_RTL}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_START_MPS=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_START_MPS}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_FULL_MPS=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_FULL_MPS}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_MAX_ABS_VSPEED_MPS=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_MAX_ABS_VSPEED_MPS}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MIN_H_M=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MIN_H_M}
PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MAX_H_M=${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MAX_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ENABLE=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ENABLE}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_MISSION=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_MISSION}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_RTL=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_RTL}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_START_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_START_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_FULL_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_FULL_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_START_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_START_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_FULL_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_FULL_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_SCORE_GAIN=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_SCORE_GAIN}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_PERSISTENCE_UPDATES=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_PERSISTENCE_UPDATES}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_HOLD_SEC=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_HOLD_SEC}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ATTACK_SEC=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ATTACK_SEC}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_DECAY_SEC=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_DECAY_SEC}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MIN_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MIN_H_M}
PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MAX_H_M=${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MAX_H_M}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_ENABLE=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_ENABLE}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_STD_DEG=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_STD_DEG}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_RESIDUAL_DEG=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_RESIDUAL_DEG}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_RESIDUAL_DEG=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_RESIDUAL_DEG}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_GYRO_DEG_S=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_GYRO_DEG_S}
PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_SOURCE_YAW_RATE_DEG_S=${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_SOURCE_YAW_RATE_DEG_S}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_ENABLE=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_ENABLE}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_MISSION=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_MISSION}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_RTL=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_RTL}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_ARMED_CRUISE=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_ARMED_CRUISE}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_POST_TURN=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_POST_TURN}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_TURN=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_TURN}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_UPDATE=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_UPDATE}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_YAW_STD_FLOOR_DEG=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_YAW_STD_FLOOR_DEG}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_RESIDUAL_DEG=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_RESIDUAL_DEG}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RESIDUAL_DEG=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RESIDUAL_DEG}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_HORIZONTAL_SPEED_MPS=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_HORIZONTAL_SPEED_MPS}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_ABS_VERTICAL_SPEED_MPS=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_ABS_VERTICAL_SPEED_MPS}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_GYRO_DEG_S=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_GYRO_DEG_S}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_SOURCE_YAW_RATE_DEG_S=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_SOURCE_YAW_RATE_DEG_S}
PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RATE_HZ=${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RATE_HZ}
PX4_SAFE_START_PAIR_LOGGER=${PX4_SAFE_START_PAIR_LOGGER}
PX4_SAFE_PAIR_LOGGER_CSV_PATH=${PX4_SAFE_PAIR_LOGGER_CSV_PATH}
PX4_SAFE_PAIR_LOGGER_RATE_HZ=${PX4_SAFE_PAIR_LOGGER_RATE_HZ}
PX4_SAFE_PAIR_LOGGER_SYNC_TOLERANCE_MS=${PX4_SAFE_PAIR_LOGGER_SYNC_TOLERANCE_MS}
PX4_SAFE_GPS_PROBE_CSV_PATH=${PX4_SAFE_GPS_PROBE_CSV_PATH}
PX4_SAFE_GPS_PROBE_SECOND_CSV_PATH=${PX4_SAFE_GPS_PROBE_SECOND_CSV_PATH}
PX4_SAFE_GPS_PROBE_PAIR_AFTER_NEWER_POSE=${PX4_SAFE_GPS_PROBE_PAIR_AFTER_NEWER_POSE}
PX4_SAFE_GPS_PROBE_MAX_PAIR_WAIT_SEC=${PX4_SAFE_GPS_PROBE_MAX_PAIR_WAIT_SEC}
EOF
}

summarize_run() {
  local run_dir="$1"
  local gnss_csv="${run_dir}/gnss_update_debug.csv"
  local gnss_nis_csv="${PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_CSV_PATH:-${run_dir}/gnss_nis_debug.csv}"
  local horizontal_consistency_csv="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_DEBUG_CSV_PATH:-${run_dir}/horizontal_consistency_debug.csv}"
  local heading_csv="${run_dir}/heading_update_debug.csv"
  local state_publish_csv="${run_dir}/state_publish_debug.csv"
  local compare_csv="${run_dir}/comparison_metrics.csv"
  local pair_csv="${run_dir}/ekf_iekf_pairs.csv"
  local gps_pose_csv="${run_dir}/gps_vs_pose.csv"
  local gps_raw_csv="${run_dir}/gps_vs_second_pose.csv"

  printf 'run_dir=%s\n' "${run_dir}"
  printf 'comparison_metrics_csv_present=%s\n' "$([[ -s "${compare_csv}" ]] && echo 1 || echo 0)"
  printf 'ekf_iekf_pair_csv_present=%s\n' "$([[ -s "${pair_csv}" ]] && echo 1 || echo 0)"
  printf 'gnss_update_debug_csv_present=%s\n' "$([[ -s "${gnss_csv}" ]] && echo 1 || echo 0)"
  printf 'gnss_nis_debug_csv_present=%s\n' "$([[ -s "${gnss_nis_csv}" ]] && echo 1 || echo 0)"
  printf 'horizontal_consistency_debug_csv_present=%s\n' "$([[ -s "${horizontal_consistency_csv}" ]] && echo 1 || echo 0)"
  printf 'heading_update_debug_csv_present=%s\n' "$([[ -s "${heading_csv}" ]] && echo 1 || echo 0)"
  printf 'state_publish_debug_csv_present=%s\n' "$([[ -s "${state_publish_csv}" ]] && echo 1 || echo 0)"
  printf 'gps_vs_pose_csv_present=%s\n' "$([[ -s "${gps_pose_csv}" ]] && echo 1 || echo 0)"
  printf 'gps_vs_second_pose_csv_present=%s\n' "$([[ -s "${gps_raw_csv}" ]] && echo 1 || echo 0)"
  printf 'comparison_metrics_rows=%s\n' "$(csv_rows "${compare_csv}")"
  printf 'ekf_iekf_pair_rows=%s\n' "$(csv_rows "${pair_csv}")"
  printf 'gnss_nis_debug_rows=%s\n' "$(csv_rows "${gnss_nis_csv}")"
  printf 'horizontal_consistency_debug_rows=%s\n' "$(csv_rows "${horizontal_consistency_csv}")"
  printf 'heading_update_debug_rows=%s\n' "$(csv_rows "${heading_csv}")"
  printf 'state_publish_debug_rows=%s\n' "$(csv_rows "${state_publish_csv}")"
  printf 'gps_vs_pose_rows=%s\n' "$(csv_rows "${gps_pose_csv}")"
  printf 'gps_vs_second_pose_rows=%s\n' "$(csv_rows "${gps_raw_csv}")"

  if [[ -s "${pair_csv}" ]]; then
    awk -F, '
      function get(name,    idx) {
        idx = header[name]
        if (idx == 0) {
          return ""
        }
        return $(idx)
      }

      function finite(value) {
        return value != "" && value != "nan" && value != "-nan" && value != "inf" && value != "-inf"
      }

      function abs_num(value) {
        return value < 0 ? -value : value
      }

      function add_metric(prefix, value) {
        if (!finite(value)) {
          return
        }
        sum[prefix] += value + 0.0
        count[prefix] += 1
        if (!(prefix in max) || value + 0.0 > max[prefix]) {
          max[prefix] = value + 0.0
        }
      }

      NR == 1 {
        for (i = 1; i <= NF; ++i) {
          gsub(/\r$/, "", $i)
          header[$i] = i
        }
        next
      }

      {
        rows += 1
        if ((get("mavros_armed") + 0) != 0) {
          armed_rows += 1
          if ((get("alignment_ready") + 0) != 0) {
            aligned_armed_rows += 1
            add_metric("armed_position_error_xy_m", get("position_error_xy_m"))
            add_metric("armed_position_error_norm_m", get("position_error_norm_m"))
            add_metric("armed_velocity_error_norm_mps", get("velocity_error_norm_mps"))
            add_metric("armed_abs_yaw_error_deg", abs_num(get("yaw_error_deg") + 0.0))
          }
        }
        if ((get("alignment_ready") + 0) != 0) {
          aligned_rows += 1
          add_metric("position_error_xy_m", get("position_error_xy_m"))
          add_metric("position_error_norm_m", get("position_error_norm_m"))
          add_metric("velocity_error_norm_mps", get("velocity_error_norm_mps"))
          add_metric("abs_yaw_error_deg", abs_num(get("yaw_error_deg") + 0.0))
          add_metric("abs_sync_dt_ms", abs_num(get("sync_dt_ms") + 0.0))
        }
      }

      END {
        print "ekf_iekf_pair_rows_seen=" (rows + 0)
        print "ekf_iekf_pair_aligned_rows=" (aligned_rows + 0)
        print "ekf_iekf_pair_armed_rows=" (armed_rows + 0)
        print "ekf_iekf_pair_aligned_armed_rows=" (aligned_armed_rows + 0)
        for (key in count) {
          if (count[key] > 0) {
            printf "ekf_iekf_pair_%s_mean=%.4f\n", key, sum[key] / count[key]
            printf "ekf_iekf_pair_%s_max=%.4f\n", key, max[key]
          }
        }
      }
    ' "${pair_csv}" | sort
  fi

  if [[ -s "${gps_raw_csv}" ]]; then
    awk -F, '
      function get(name,    idx) {
        idx = header[name]
        if (idx == 0) {
          return ""
        }
        return $(idx)
      }

      function finite(value) {
        return value != "" && value != "nan" && value != "-nan" && value != "inf" && value != "-inf"
      }

      NR == 1 {
        for (i = 1; i <= NF; ++i) {
          header[$i] = i
        }
        has_pair_diag = header["pose_waited_for_newer_stamp"] != 0
        next
      }

      has_pair_diag {
        rows += 1
        if ((get("pose_waited_for_newer_stamp") + 0) != 0) {
          waited_rows += 1
        }
        if (finite(get("pending_pair_age_sec"))) {
          pending_age_sum += get("pending_pair_age_sec")
          pending_age_count += 1
        }
        if (finite(get("same_stamp_pose_count"))) {
          same_stamp_count_sum += get("same_stamp_pose_count")
          same_stamp_count_count += 1
        }
        if (finite(get("pose_buffer_latest_stamp_sec")) && finite(get("gps_stamp_sec"))) {
          latest_minus_gps_sum += get("pose_buffer_latest_stamp_sec") - get("gps_stamp_sec")
          latest_minus_gps_count += 1
        }
      }

      END {
        if (has_pair_diag) {
          print "gps_vs_second_pose_pair_diag_rows=" (rows + 0)
          print "gps_vs_second_pose_pair_waited_for_newer_stamp_rows=" (waited_rows + 0)
          if (pending_age_count > 0) {
            printf "gps_vs_second_pose_pending_pair_age_mean_sec=%.4f\n", pending_age_sum / pending_age_count
          } else {
            print "gps_vs_second_pose_pending_pair_age_mean_sec="
          }
          if (same_stamp_count_count > 0) {
            printf "gps_vs_second_pose_same_stamp_pose_count_mean=%.2f\n", same_stamp_count_sum / same_stamp_count_count
          } else {
            print "gps_vs_second_pose_same_stamp_pose_count_mean="
          }
          if (latest_minus_gps_count > 0) {
            printf "gps_vs_second_pose_latest_pose_minus_gps_mean_sec=%.4f\n", latest_minus_gps_sum / latest_minus_gps_count
          } else {
            print "gps_vs_second_pose_latest_pose_minus_gps_mean_sec="
          }
        }
      }
    ' "${gps_raw_csv}"
  fi

  if [[ -s "${state_publish_csv}" ]]; then
    awk -F, '
      function get(name,    idx) {
        idx = header[name]
        if (idx == 0) {
          return ""
        }
        return $(idx)
      }

      function finite(value) {
        return value != "" && value != "nan" && value != "-nan" && value != "inf" && value != "-inf"
      }

      function add(name, value) {
        if (finite(value)) {
          sum[name] += value
          count[name] += 1
        }
      }

      NR == 1 {
        for (i = 1; i <= NF; ++i) {
          header[$i] = i
        }
        next
      }

      {
        rows += 1
        if ((get("mavros_armed") + 0) != 0) {
          armed_rows += 1
          add("armed_core_gnss_diff_h_m", get("core_gnss_diff_h_m"))
        }
        if ((get("odom_uses_gnss_pose") + 0) != 0) {
          odom_uses_gnss_pose_rows += 1
        }
        add("core_time_minus_ros_sec", get("core_time_minus_ros_sec"))
        add("gnss_update_time_minus_ros_sec", get("gnss_update_time_minus_ros_sec"))
        add("gnss_source_time_minus_ros_sec", get("gnss_source_time_minus_ros_sec"))
      }

      END {
        print "state_publish_debug_rows_seen=" (rows + 0)
        print "state_publish_debug_armed_rows=" (armed_rows + 0)
        print "state_publish_debug_odom_uses_gnss_pose_rows=" (odom_uses_gnss_pose_rows + 0)
        if (count["core_time_minus_ros_sec"] > 0) {
          printf "state_publish_debug_core_time_minus_ros_mean_sec=%.6f\n", sum["core_time_minus_ros_sec"] / count["core_time_minus_ros_sec"]
        } else {
          print "state_publish_debug_core_time_minus_ros_mean_sec="
        }
        if (count["gnss_update_time_minus_ros_sec"] > 0) {
          printf "state_publish_debug_gnss_update_time_minus_ros_mean_sec=%.6f\n", sum["gnss_update_time_minus_ros_sec"] / count["gnss_update_time_minus_ros_sec"]
        } else {
          print "state_publish_debug_gnss_update_time_minus_ros_mean_sec="
        }
        if (count["gnss_source_time_minus_ros_sec"] > 0) {
          printf "state_publish_debug_gnss_source_time_minus_ros_mean_sec=%.6f\n", sum["gnss_source_time_minus_ros_sec"] / count["gnss_source_time_minus_ros_sec"]
        } else {
          print "state_publish_debug_gnss_source_time_minus_ros_mean_sec="
        }
        if (count["armed_core_gnss_diff_h_m"] > 0) {
          printf "state_publish_debug_armed_core_gnss_diff_h_mean_m=%.4f\n", sum["armed_core_gnss_diff_h_m"] / count["armed_core_gnss_diff_h_m"]
        } else {
          print "state_publish_debug_armed_core_gnss_diff_h_mean_m="
        }
      }
    ' "${state_publish_csv}"
  fi

  if [[ -s "${heading_csv}" ]]; then
    awk -F, '
      function get(name,    idx) {
        idx = header[name]
        if (idx == 0) {
          return ""
        }
        return $(idx)
      }

      function truthy(value) {
        return value != "" && value != "nan" && value != "-nan" && (value + 0) != 0
      }

      NR == 1 {
        for (i = 1; i <= NF; ++i) {
          header[$i] = i
        }
        next
      }

      {
        event_type = get("event_type")
        heading_mode = get("heading_mode")
        if (event_type == "ingest") {
          ingest_rows += 1
          if (heading_mode == "post_turn_cruise_track") {
            post_turn_cruise_track_ingest_rows += 1
          }
          if (heading_mode == "armed_cruise_track") {
            armed_cruise_track_ingest_rows += 1
            if (truthy(get("post_turn_window_active_before"))) {
              armed_cruise_track_window_before_rows += 1
            }
            if (truthy(get("post_turn_followthrough_active_before"))) {
              armed_cruise_track_followthrough_before_rows += 1
            }
            if (truthy(get("post_turn_context_active_before"))) {
              armed_cruise_track_context_before_rows += 1
            }
          }
          if (truthy(get("used_post_turn_cruise_track"))) {
            used_post_turn_cruise_track_rows += 1
          }
          if (truthy(get("post_turn_low_hspeed_cluster_ok"))) {
            post_turn_low_hspeed_cluster_rows += 1
          }
          if (truthy(get("used_armed_cruise_track"))) {
            used_armed_cruise_track_rows += 1
          }
          if (truthy(get("heading_update_underreacted"))) {
            heading_update_underreacted_rows += 1
          }
        } else if (event_type == "underreaction_force_relock") {
          underreaction_force_relock_rows += 1
        }
      }

      END {
        print "heading_update_debug_ingest_rows=" (ingest_rows + 0)
        print "heading_update_debug_post_turn_cruise_track_ingest_rows=" (post_turn_cruise_track_ingest_rows + 0)
        print "heading_update_debug_armed_cruise_track_ingest_rows=" (armed_cruise_track_ingest_rows + 0)
        print "heading_update_debug_armed_cruise_track_window_before_rows=" (armed_cruise_track_window_before_rows + 0)
        print "heading_update_debug_armed_cruise_track_followthrough_before_rows=" (armed_cruise_track_followthrough_before_rows + 0)
        print "heading_update_debug_armed_cruise_track_context_before_rows=" (armed_cruise_track_context_before_rows + 0)
        print "heading_update_debug_used_post_turn_cruise_track_rows=" (used_post_turn_cruise_track_rows + 0)
        print "heading_update_debug_post_turn_low_hspeed_cluster_rows=" (post_turn_low_hspeed_cluster_rows + 0)
        print "heading_update_debug_used_armed_cruise_track_rows=" (used_armed_cruise_track_rows + 0)
        print "heading_update_debug_heading_update_underreacted_rows=" (heading_update_underreacted_rows + 0)
        print "heading_update_debug_underreaction_force_relock_rows=" (underreaction_force_relock_rows + 0)
      }
    ' "${heading_csv}"
  fi

  if [[ ! -s "${gnss_csv}" ]]; then
    printf 'summary_error=missing_gnss_update_debug_csv\n'
    return 1
  fi

  awk -F, '
    function get(name,    idx) {
      idx = header[name]
      if (idx == 0) {
        return ""
      }
      return $(idx)
    }

    function is_nan(value) {
      return value == "" || value == "nan" || value == "-nan" || value == "NaN" || value == "-NaN"
    }

    function abs_num(value) {
      return (value < 0.0) ? -value : value
    }

    NR == 1 {
      for (i = 1; i <= NF; ++i) {
        header[$i] = i
      }
      have_postflight_active = ("post_flight_vertical_cov_reopen_active" in header)
      have_postflight_applied = ("post_flight_vertical_cov_reopen_applied" in header)
      have_lag_comp_active = ("position_lag_compensation_active" in header)
      have_lag_comp_sec = ("position_lag_compensation_sec" in header)
      have_lag_comp_n = ("position_lag_compensation_n_m" in header)
      have_lag_comp_e = ("position_lag_compensation_e_m" in header)
      have_lag_comp_u = ("position_lag_compensation_u_m" in header)
      have_terminal_context = ("terminal_descent_context" in header)
      have_terminal_hzero_active = ("terminal_descent_horizontal_zero_velocity_active" in header)
      have_terminal_hzero_applied = ("terminal_descent_horizontal_zero_velocity_applied" in header)
      next
    }

    {
      armed_raw = get("mavros_armed")
      ros_raw = get("ros_time_sec")
      seq_raw = get("sequence")

      if (is_nan(armed_raw) || is_nan(ros_raw) || is_nan(seq_raw)) {
        next
      }

      armed = armed_raw + 0
      ros = ros_raw + 0
      seq = seq_raw + 0

      if (have_lag_comp_active) {
        lag_comp_active = get("position_lag_compensation_active")
        if (!is_nan(lag_comp_active) && (lag_comp_active + 0) != 0) {
          lag_comp_active_rows += 1
          if (armed != 0) {
            lag_comp_armed_active_rows += 1
          }
          if (have_lag_comp_sec) {
            lag_comp_sec = get("position_lag_compensation_sec")
            if (!is_nan(lag_comp_sec)) {
              lag_comp_sec_sum += lag_comp_sec + 0.0
              lag_comp_sec_count += 1
            }
          }
          if (have_lag_comp_n && have_lag_comp_e) {
            lag_comp_n = get("position_lag_compensation_n_m")
            lag_comp_e = get("position_lag_compensation_e_m")
            if (!is_nan(lag_comp_n) && !is_nan(lag_comp_e)) {
              lag_comp_h_sum += sqrt((lag_comp_n + 0.0) * (lag_comp_n + 0.0) + (lag_comp_e + 0.0) * (lag_comp_e + 0.0))
              lag_comp_h_count += 1
            }
          }
          if (have_lag_comp_u) {
            lag_comp_u = get("position_lag_compensation_u_m")
            if (!is_nan(lag_comp_u)) {
              lag_comp_abs_u_sum += abs_num(lag_comp_u + 0.0)
              lag_comp_abs_u_count += 1
            }
          }
        }
      }

      if (have_terminal_context) {
        terminal_context = get("terminal_descent_context")
        if (!is_nan(terminal_context) && (terminal_context + 0) != 0) {
          terminal_context_rows += 1
          if (armed != 0) {
            terminal_context_armed_rows += 1
          }
        }
      }

      if (have_terminal_hzero_active) {
        terminal_hzero_active = get("terminal_descent_horizontal_zero_velocity_active")
        if (!is_nan(terminal_hzero_active) && (terminal_hzero_active + 0) != 0) {
          terminal_hzero_active_rows += 1
          if (armed != 0) {
            terminal_hzero_armed_active_rows += 1
          }
        }
      }

      if (have_terminal_hzero_applied) {
        terminal_hzero_applied = get("terminal_descent_horizontal_zero_velocity_applied")
        if (!is_nan(terminal_hzero_applied) && (terminal_hzero_applied + 0) != 0) {
          terminal_hzero_applied_rows += 1
          if (armed != 0) {
            terminal_hzero_armed_applied_rows += 1
          }
        }
      }

      if (!have_prev_armed) {
        prev_armed = armed
        have_prev_armed = 1
      }

      if (armed != prev_armed) {
        if (!have_arm_transition && prev_armed == 0 && armed == 1) {
          have_arm_transition = 1
          arm_transition_seq = seq
          arm_transition_ros = ros
        }
        if (!have_disarm_transition && prev_armed == 1 && armed == 0) {
          have_disarm_transition = 1
          disarm_transition_seq = seq
          disarm_transition_ros = ros
        }
        prev_armed = armed
      }

      if (have_disarm_transition && ros >= disarm_transition_ros) {
        postflight_rows += 1
        last_postflight_seq = seq
        last_postflight_ros = ros

        core_gnss_diff_u = get("core_gnss_diff_u_m")
        if (!is_nan(core_gnss_diff_u)) {
          postflight_core_gnss_diff_u_sum += abs_num(core_gnss_diff_u + 0.0)
          postflight_core_gnss_diff_u_count += 1
        }

        last_pos_residual_u = get("last_position_residual_u_m")
        if (!is_nan(last_pos_residual_u)) {
          postflight_last_pos_residual_u_sum += abs_num(last_pos_residual_u + 0.0)
          postflight_last_pos_residual_u_count += 1
        }

        core_pos_std_d = get("core_pos_std_d_m")
        if (!is_nan(core_pos_std_d)) {
          postflight_core_pos_std_d_sum += core_pos_std_d + 0.0
          postflight_core_pos_std_d_count += 1
        }

        vertical_active = get("vertical_cov_reopen_active")
        if (!is_nan(vertical_active) && (vertical_active + 0) != 0) {
          combined_vertical_active_rows += 1
        }

        vertical_applied = get("vertical_cov_reopen_applied")
        if (!is_nan(vertical_applied) && (vertical_applied + 0) != 0) {
          combined_vertical_applied_rows += 1
        }

        if (have_postflight_active) {
          postflight_active = get("post_flight_vertical_cov_reopen_active")
          if (!is_nan(postflight_active) && (postflight_active + 0) != 0) {
            postflight_active_rows += 1
          }
        }

        if (have_postflight_applied) {
          postflight_applied = get("post_flight_vertical_cov_reopen_applied")
          if (!is_nan(postflight_applied) && (postflight_applied + 0) != 0) {
            postflight_applied_rows += 1
          }
        }
      }
    }

    END {
      print "gnss_update_debug_rows=" NR - 1
      print "armed_transition_present=" (have_arm_transition ? 1 : 0)
      if (have_arm_transition) {
        printf("armed_transition_seq=%d\n", arm_transition_seq)
        printf("armed_transition_ros_time_sec=%.3f\n", arm_transition_ros)
      } else {
        print "armed_transition_seq="
        print "armed_transition_ros_time_sec="
      }

      print "disarm_transition_present=" (have_disarm_transition ? 1 : 0)
      if (have_disarm_transition) {
        printf("disarm_transition_seq=%d\n", disarm_transition_seq)
        printf("disarm_transition_ros_time_sec=%.3f\n", disarm_transition_ros)
      } else {
        print "disarm_transition_seq="
        print "disarm_transition_ros_time_sec="
      }

      print "postflight_rows=" (postflight_rows + 0)
      if (postflight_rows > 0) {
        printf("last_postflight_seq=%d\n", last_postflight_seq)
        printf("last_postflight_ros_time_sec=%.3f\n", last_postflight_ros)
      } else {
        print "last_postflight_seq="
        print "last_postflight_ros_time_sec="
      }

      print "post_flight_vertical_cov_reopen_columns_present=" ((have_postflight_active && have_postflight_applied) ? 1 : 0)
      print "post_flight_vertical_cov_reopen_active_rows=" (postflight_active_rows + 0)
      print "post_flight_vertical_cov_reopen_applied_rows=" (postflight_applied_rows + 0)
      print "combined_vertical_cov_reopen_active_rows=" (combined_vertical_active_rows + 0)
      print "combined_vertical_cov_reopen_applied_rows=" (combined_vertical_applied_rows + 0)
      print "gnss_position_lag_compensation_columns_present=" ((have_lag_comp_active && have_lag_comp_sec && have_lag_comp_n && have_lag_comp_e && have_lag_comp_u) ? 1 : 0)
      print "gnss_position_lag_compensation_active_rows=" (lag_comp_active_rows + 0)
      print "gnss_position_lag_compensation_armed_active_rows=" (lag_comp_armed_active_rows + 0)
      print "terminal_descent_context_columns_present=" (have_terminal_context ? 1 : 0)
      print "terminal_descent_context_rows=" (terminal_context_rows + 0)
      print "terminal_descent_context_armed_rows=" (terminal_context_armed_rows + 0)
      print "terminal_descent_horizontal_zero_velocity_columns_present=" ((have_terminal_hzero_active && have_terminal_hzero_applied) ? 1 : 0)
      print "terminal_descent_horizontal_zero_velocity_active_rows=" (terminal_hzero_active_rows + 0)
      print "terminal_descent_horizontal_zero_velocity_applied_rows=" (terminal_hzero_applied_rows + 0)
      print "terminal_descent_horizontal_zero_velocity_armed_active_rows=" (terminal_hzero_armed_active_rows + 0)
      print "terminal_descent_horizontal_zero_velocity_armed_applied_rows=" (terminal_hzero_armed_applied_rows + 0)
      if (lag_comp_sec_count > 0) {
        printf("gnss_position_lag_compensation_mean_sec=%.4f\n", lag_comp_sec_sum / lag_comp_sec_count)
      } else {
        print "gnss_position_lag_compensation_mean_sec="
      }
      if (lag_comp_h_count > 0) {
        printf("gnss_position_lag_compensation_mean_h_m=%.4f\n", lag_comp_h_sum / lag_comp_h_count)
      } else {
        print "gnss_position_lag_compensation_mean_h_m="
      }
      if (lag_comp_abs_u_count > 0) {
        printf("gnss_position_lag_compensation_mean_abs_u_m=%.4f\n", lag_comp_abs_u_sum / lag_comp_abs_u_count)
      } else {
        print "gnss_position_lag_compensation_mean_abs_u_m="
      }

      if (postflight_core_gnss_diff_u_count > 0) {
        printf("postflight_mean_abs_core_gnss_diff_u_m=%.4f\n", postflight_core_gnss_diff_u_sum / postflight_core_gnss_diff_u_count)
      } else {
        print "postflight_mean_abs_core_gnss_diff_u_m="
      }

      if (postflight_last_pos_residual_u_count > 0) {
        printf("postflight_mean_abs_last_pos_residual_u_m=%.4f\n", postflight_last_pos_residual_u_sum / postflight_last_pos_residual_u_count)
      } else {
        print "postflight_mean_abs_last_pos_residual_u_m="
      }

      if (postflight_core_pos_std_d_count > 0) {
        printf("postflight_mean_core_pos_std_d_m=%.4f\n", postflight_core_pos_std_d_sum / postflight_core_pos_std_d_count)
      } else {
        print "postflight_mean_core_pos_std_d_m="
      }

      print "manual14_baseline_postflight_mean_abs_core_gnss_diff_u_m=0.2517"
      print "manual14_baseline_postflight_mean_abs_last_pos_residual_u_m=0.2581"
      print "manual14_baseline_postflight_mean_core_pos_std_d_m=0.0380"
    }
  ' "${gnss_csv}"

  if [[ -s "${gps_raw_csv}" ]]; then
    python3 - "${gnss_csv}" "${gps_raw_csv}" <<'PY'
import bisect
import csv
import math
import sys


def as_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return math.nan


def truthy(value):
    return str(value).strip().lower() in ("1", "true", "yes")


def mean(values):
    vals = [v for v in values if math.isfinite(v)]
    if not vals:
        return math.nan
    return sum(vals) / len(vals)


def nearest(rows, times, target):
    index = bisect.bisect_left(times, target)
    candidates = []
    if index < len(rows):
        candidates.append((abs(times[index] - target), rows[index]))
    if index > 0:
        candidates.append((abs(times[index - 1] - target), rows[index - 1]))
    if not candidates:
        return None, math.nan
    return min(candidates, key=lambda item: item[0])


gnss_path, gps_raw_path = sys.argv[1], sys.argv[2]
with open(gnss_path, newline="") as handle:
    gnss_rows = list(csv.DictReader(handle))
gnss_rows.sort(key=lambda row: as_float(row.get("ros_time_sec")))
gnss_times = [as_float(row.get("ros_time_sec")) for row in gnss_rows]

groups = {
    "armed": lambda g: truthy(g.get("mavros_armed")),
    "turning": lambda g: truthy(g.get("mavros_armed")) and truthy(g.get("turning_now")),
    "post_only": lambda g: (
        truthy(g.get("mavros_armed"))
        and truthy(g.get("post_turn_context"))
        and not truthy(g.get("turning_now"))
    ),
    "turn_or_post": lambda g: (
        truthy(g.get("mavros_armed"))
        and (truthy(g.get("turning_now")) or truthy(g.get("post_turn_context")))
    ),
    "cruise": lambda g: truthy(g.get("mavros_armed")) and truthy(g.get("armed_cruise_context")),
    "low_speed": lambda g: (
        truthy(g.get("mavros_armed"))
        and math.isfinite(as_float(g.get("horizontal_speed_mps")))
        and as_float(g.get("horizontal_speed_mps")) < 1.0
    ),
    "high_vertical": lambda g: (
        truthy(g.get("mavros_armed"))
        and math.isfinite(as_float(g.get("vertical_speed_mps")))
        and abs(as_float(g.get("vertical_speed_mps"))) > 0.6
    ),
}
stats = {
    name: {
        "rows": 0,
        "local_xy": [],
        "local_abs_z": [],
        "core_gnss_diff_h": [],
        "core_gnss_abs_u": [],
        "gnss_residual_xy": [],
        "gnss_residual_local6_xy": [],
        "raw_probe_residual_lag_sec": [],
    }
    for name in groups
}
join_dts = []
residual_window = []

with open(gps_raw_path, newline="") as handle:
    for row in csv.DictReader(handle):
        t = as_float(row.get("gps_stamp_sec"))
        if not math.isfinite(t):
            t = as_float(row.get("pose_stamp_sec"))
        if not math.isfinite(t):
            t = as_float(row.get("ros_time_sec"))
        if not math.isfinite(t):
            continue
        dt, match = nearest(gnss_rows, gnss_times, t)
        if match is None:
            continue
        if math.isfinite(dt):
            join_dts.append(dt)
        residual_e_m = as_float(match.get("gnss_position_residual_e_m"))
        residual_n_m = as_float(match.get("gnss_position_residual_n_m"))
        residual_xy_m = math.nan
        residual_local6_xy_m = math.nan
        if math.isfinite(residual_e_m) and math.isfinite(residual_n_m):
            residual_xy_m = math.hypot(residual_e_m, residual_n_m)
            residual_window.append((t, residual_e_m, residual_n_m))
            while len(residual_window) > 1 and (t - residual_window[0][0]) > 6.0:
                residual_window.pop(0)
            anchor = residual_window[0]
            residual_local6_xy_m = math.hypot(
                residual_e_m - anchor[1],
                residual_n_m - anchor[2],
            )
        raw_probe_residual_lag_sec = math.nan
        probe_error_e_m = as_float(row.get("error_x_m"))
        probe_error_n_m = as_float(row.get("error_y_m"))
        velocity_e_mps = as_float(match.get("native_velocity_vE_mps"))
        velocity_n_mps = as_float(match.get("native_velocity_vN_mps"))
        speed_sq_mps2 = velocity_e_mps * velocity_e_mps + velocity_n_mps * velocity_n_mps
        if (
            math.isfinite(probe_error_e_m)
            and math.isfinite(probe_error_n_m)
            and math.isfinite(residual_e_m)
            and math.isfinite(residual_n_m)
            and math.isfinite(speed_sq_mps2)
            and speed_sq_mps2 > 1.0
        ):
            delta_e_m = probe_error_e_m - residual_e_m
            delta_n_m = probe_error_n_m - residual_n_m
            raw_probe_residual_lag_sec = -(
                delta_e_m * velocity_e_mps + delta_n_m * velocity_n_mps
            ) / speed_sq_mps2
        for name, predicate in groups.items():
            if not predicate(match):
                continue
            stats[name]["rows"] += 1
            stats[name]["local_xy"].append(as_float(row.get("local_xy_error_m")))
            stats[name]["local_abs_z"].append(abs(as_float(row.get("local_error_z_m"))))
            stats[name]["core_gnss_diff_h"].append(as_float(match.get("core_gnss_diff_h_m")))
            stats[name]["core_gnss_abs_u"].append(abs(as_float(match.get("core_gnss_diff_u_m"))))
            stats[name]["gnss_residual_xy"].append(residual_xy_m)
            stats[name]["gnss_residual_local6_xy"].append(residual_local6_xy_m)
            stats[name]["raw_probe_residual_lag_sec"].append(raw_probe_residual_lag_sec)

if join_dts:
    print(f"phase_metric_join_max_dt_sec={max(join_dts):.4f}")
else:
    print("phase_metric_join_max_dt_sec=")

for name in ("armed", "turning", "post_only", "turn_or_post", "cruise", "low_speed", "high_vertical"):
    item = stats[name]
    print(f"phase_metric_{name}_rows={item['rows']}")
    for key, values in (
        ("local_xy_mean_m", item["local_xy"]),
        ("local_abs_z_mean_m", item["local_abs_z"]),
        ("core_gnss_diff_h_mean_m", item["core_gnss_diff_h"]),
        ("core_gnss_abs_u_mean_m", item["core_gnss_abs_u"]),
        ("gnss_residual_xy_mean_m", item["gnss_residual_xy"]),
        ("gnss_residual_local6_xy_mean_m", item["gnss_residual_local6_xy"]),
        ("raw_probe_residual_lag_mean_sec", item["raw_probe_residual_lag_sec"]),
    ):
        value = mean(values)
        if math.isfinite(value):
            print(f"phase_metric_{name}_{key}={value:.4f}")
        else:
            print(f"phase_metric_{name}_{key}=")
PY
  fi
}

RUN_DIR="$(resolve_run_dir "${RUN_REF}")"

export RUN_DIR
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
export PX4_SAFE_PX4_WORLD="${PX4_SAFE_PX4_WORLD:-none}"
export PX4_SAFE_START_MAVROS="${PX4_SAFE_START_MAVROS:-1}"
export PX4_SAFE_START_QGC="${PX4_SAFE_START_QGC:-1}"
export PX4_SAFE_START_MONITOR="${PX4_SAFE_START_MONITOR:-0}"
export PX4_SAFE_START_COMPARE="${PX4_SAFE_START_COMPARE:-1}"
export PX4_SAFE_START_GPS_PROBES="${PX4_SAFE_START_GPS_PROBES:-1}"
export PX4_SAFE_START_PLOTJUGGLER="${PX4_SAFE_START_PLOTJUGGLER:-0}"
export PX4_SAFE_HEADLESS="${PX4_SAFE_HEADLESS:-1}"
export PX4_SAFE_NO_PXH="${PX4_SAFE_NO_PXH:-1}"
export PX4_SAFE_MAVROS_PROFILE="${PX4_SAFE_MAVROS_PROFILE:-runtime_minimal}"
export PX4_SAFE_GCS_LINK_PROFILE="${PX4_SAFE_GCS_LINK_PROFILE:-light}"
export PX4_SAFE_GCS_RATE_BPS="${PX4_SAFE_GCS_RATE_BPS:-500000}"
export PX4_SAFE_GCS_POSITION_RATE_HZ="${PX4_SAFE_GCS_POSITION_RATE_HZ:-6}"
export PX4_SAFE_GCS_ATTITUDE_RATE_HZ="${PX4_SAFE_GCS_ATTITUDE_RATE_HZ:-8}"
export PX4_SAFE_GCS_TARGET_RATE_HZ="${PX4_SAFE_GCS_TARGET_RATE_HZ:-5}"
export PX4_SAFE_GCS_SERVO_RATE_HZ="${PX4_SAFE_GCS_SERVO_RATE_HZ:-0}"
export PX4_SAFE_GCS_RC_RATE_HZ="${PX4_SAFE_GCS_RC_RATE_HZ:-0}"
export PX4_SAFE_GCS_FLOW_RATE_HZ="${PX4_SAFE_GCS_FLOW_RATE_HZ:-0}"
export PX4_SAFE_COMPARE_KF_GINS_PARAM_FILE="${PX4_SAFE_COMPARE_KF_GINS_PARAM_FILE:-${WS_ROOT}/src/kf_gins_ros2_native/config/kfgins_sim_fixed.yaml}"
export PX4_SAFE_COMPARE_KF_GINS_CORE_CONFIG_FILE="${PX4_SAFE_COMPARE_KF_GINS_CORE_CONFIG_FILE:-${WS_ROOT}/src/kf_gins_ros2_native/config/kf_gins_core_sim_no_sage.yaml}"
export PX4_SAFE_COMPARE_FORCE_ZERO_ANTLEVER="${PX4_SAFE_COMPARE_FORCE_ZERO_ANTLEVER:-true}"
export PX4_SAFE_COMPARE_ENABLE_REAL_TIME="${PX4_SAFE_COMPARE_ENABLE_REAL_TIME:-false}"
export PX4_SAFE_COMPARE_CSV_PATH="${PX4_SAFE_COMPARE_CSV_PATH:-${RUN_DIR}/comparison_metrics.csv}"
export PX4_SAFE_COMPARE_IEKF_RAW_TOPIC="${PX4_SAFE_COMPARE_IEKF_RAW_TOPIC-__disabled__}"
export PX4_SAFE_COMPARE_COMPUTE_RAW_METRICS="${PX4_SAFE_COMPARE_COMPUTE_RAW_METRICS:-false}"
export PX4_SAFE_COMPARE_RAW_CALLBACK_MODE="${PX4_SAFE_COMPARE_RAW_CALLBACK_MODE:-store}"
export PX4_SAFE_COMPARE_GNSS_UPDATE_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_GNSS_UPDATE_DEBUG_CSV_PATH:-${RUN_DIR}/gnss_update_debug.csv}"
export PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_CSV_PATH:-}"
export PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_MAX_RATE_HZ="${PX4_SAFE_COMPARE_GNSS_NIS_DEBUG_MAX_RATE_HZ:-2.0}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_DEBUG_CSV_PATH:-}"
export PX4_SAFE_COMPARE_HEADING_UPDATE_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_HEADING_UPDATE_DEBUG_CSV_PATH:-${RUN_DIR}/heading_update_debug.csv}"
	export PX4_SAFE_COMPARE_STATE_PUBLISH_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_STATE_PUBLISH_DEBUG_CSV_PATH:-${RUN_DIR}/state_publish_debug.csv}"
	export PX4_SAFE_COMPARE_PUBLISH_STATE_AFTER_GNSS_UPDATE="${PX4_SAFE_COMPARE_PUBLISH_STATE_AFTER_GNSS_UPDATE:-true}"
	export PX4_SAFE_COMPARE_PUBLISH_PX4_SPHERE_PROJECTION="${PX4_SAFE_COMPARE_PUBLISH_PX4_SPHERE_PROJECTION:-false}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ENABLE="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ENABLE:-false}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_MISSION="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_MISSION:-true}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_RTL="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_RTL:-false}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_OTHER="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_APPLY_OTHER:-false}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ALPHA="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_ALPHA:-1.2}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_DEEP_THRESHOLD_MPS2="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_DEEP_THRESHOLD_MPS2:--0.205}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_FRAC_THRESHOLD="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_FRAC_THRESHOLD:-0.4}"
	export PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_HISTORY_START_SEC="${PX4_SAFE_COMPARE_ACCBIAS_Z_HISTORY_PROJECTION_HISTORY_START_SEC:-40.0}"
	export PX4_SAFE_COMPARE_PUBLISH_STAMP_MODE="${PX4_SAFE_COMPARE_PUBLISH_STAMP_MODE:-ros_now}"
	export PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_FUTURE_SEC="${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_FUTURE_SEC:-0.08}"
	export PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_PAST_SEC="${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_MAX_PAST_SEC:-0.25}"
	export PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_OFFSET_BIAS_SEC="${PX4_SAFE_COMPARE_PUBLISH_CORE_STAMP_OFFSET_BIAS_SEC:-0.0}"
	export PX4_SAFE_COMPARE_RAW_ODOM_DECIMATION="${PX4_SAFE_COMPARE_RAW_ODOM_DECIMATION:-50}"
export PX4_SAFE_COMPARE_PATH_PUBLISH_RATE_HZ="${PX4_SAFE_COMPARE_PATH_PUBLISH_RATE_HZ:-5.0}"
export PX4_SAFE_COMPARE_POSE_DECIMATION="${PX4_SAFE_COMPARE_POSE_DECIMATION:-5}"
export PX4_SAFE_COMPARE_MAX_PATH_POINTS="${PX4_SAFE_COMPARE_MAX_PATH_POINTS:-20000}"
export PX4_SAFE_COMPARE_CORE_PROCESSING_ENABLE="${PX4_SAFE_COMPARE_CORE_PROCESSING_ENABLE:-true}"
export PX4_SAFE_COMPARE_CORE_IMU_DECIMATION="${PX4_SAFE_COMPARE_CORE_IMU_DECIMATION:-1}"
export PX4_SAFE_COMPARE_CORE_MAX_IMU_RATE_HZ="${PX4_SAFE_COMPARE_CORE_MAX_IMU_RATE_HZ:-0.0}"
export PX4_SAFE_COMPARE_EKF2_USE_INPUT_STAMP="${PX4_SAFE_COMPARE_EKF2_USE_INPUT_STAMP:-true}"
export PX4_SAFE_COMPARE_GNSS_RELAY_MODE="${PX4_SAFE_COMPARE_GNSS_RELAY_MODE:-px4_sensor_gps}"
export PX4_SAFE_COMPARE_ENABLE_GNSS_RELAY="${PX4_SAFE_COMPARE_ENABLE_GNSS_RELAY:-true}"
export PX4_SAFE_COMPARE_GNSS_RELAY_SUBSCRIBE_ENABLE="${PX4_SAFE_COMPARE_GNSS_RELAY_SUBSCRIBE_ENABLE:-true}"
export PX4_SAFE_COMPARE_GNSS_RELAY_PUBLISH_ENABLE="${PX4_SAFE_COMPARE_GNSS_RELAY_PUBLISH_ENABLE:-true}"
export PX4_SAFE_COMPARE_ENABLE_GPS_DROPZONES="${PX4_SAFE_COMPARE_ENABLE_GPS_DROPZONES:-false}"
export PX4_SAFE_COMPARE_INJECT_DROPZONE_GPS_TO_PX4="${PX4_SAFE_COMPARE_INJECT_DROPZONE_GPS_TO_PX4:-true}"
export PX4_SAFE_COMPARE_PX4_GPS_INJECTION_MODE="${PX4_SAFE_COMPARE_PX4_GPS_INJECTION_MODE:-hil_gps}"
export PX4_SAFE_COMPARE_PX4_SET_PARAMS="${PX4_SAFE_COMPARE_PX4_SET_PARAMS:-true}"
export PX4_SAFE_COMPARE_ENABLE_EKF2_RELAY="${PX4_SAFE_COMPARE_ENABLE_EKF2_RELAY:-true}"
export PX4_SAFE_COMPARE_ENABLE_KF_GINS="${PX4_SAFE_COMPARE_ENABLE_KF_GINS:-true}"
export PX4_SAFE_COMPARE_ENABLE_STATIC_TF="${PX4_SAFE_COMPARE_ENABLE_STATIC_TF:-true}"
export PX4_SAFE_COMPARE_USE_SIM_GNSS_STD="${PX4_SAFE_COMPARE_USE_SIM_GNSS_STD:-true}"
export PX4_SAFE_COMPARE_SIM_GNSS_STD_H_M="${PX4_SAFE_COMPARE_SIM_GNSS_STD_H_M:-0.08}"
export PX4_SAFE_COMPARE_SIM_GNSS_STD_U_M="${PX4_SAFE_COMPARE_SIM_GNSS_STD_U_M:-0.10}"
export PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_ENABLE="${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_ENABLE:-false}"
export PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_SEC="${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_SEC:-0.25}"
export PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MAX_SEC="${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MAX_SEC:-0.50}"
export PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MIN_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POS_LAG_COMP_MIN_SPEED_MPS:-0.50}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_ENABLE="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_ENABLE:-true}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_MISSION="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_RTL="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_RTL:-true}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_OTHER="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_OVERRIDE_APPLY_OTHER:-true}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_H_M="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_H_M:-0.06}"
export PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_U_M="${PX4_SAFE_COMPARE_ARMED_CRUISE_GNSS_POS_STD_U_M:-0.08}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_ENABLE="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_ENABLE:-false}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_MISSION="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_RTL="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_START_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_START_H_M:-0.25}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_FULL_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_RESIDUAL_FULL_H_M:-0.45}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MIN_HORIZONTAL_SPEED_MPS:-0.5}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_PERSISTENCE_UPDATES:-1}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MIN_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MIN_H_M:-0.04}"
export PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MAX_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_RESPONSE_BOOST_STD_MAX_H_M:-0.06}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_ENABLE="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_ENABLE:-false}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_MISSION="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_RTL="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_REQUIRE_ARMED_CRUISE="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_REQUIRE_ARMED_CRUISE:-true}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_TURNING="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_TURNING:-true}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_POST_TURN="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_BLOCK_POST_TURN:-true}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_START_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_START_H_M:-0.15}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_FULL_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_RESIDUAL_FULL_H_M:-0.35}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_START="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_START:-6.0}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_FULL="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_HNIS_FULL:-20.0}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_LOW="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_LOW:-0.10}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_HIGH="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PREV_GAIN_HIGH:-0.18}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MIN_HORIZONTAL_SPEED_MPS:-3.0}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_PERSISTENCE_UPDATES:-1}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MIN_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MIN_H_M:-0.03}"
export PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MAX_H_M="${PX4_SAFE_COMPARE_GNSS_POSITION_GAIN_RESPONSE_STD_MAX_H_M:-0.06}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ENABLE="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ENABLE:-false}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_MISSION="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_RTL="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_START_DEG_S="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_START_DEG_S:-6.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_FULL_DEG_S="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRO_FULL_DEG_S:-20.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MIN_HORIZONTAL_SPEED_MPS:-0.5}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ARW_Q_SCALE_MAX="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ARW_Q_SCALE_MAX:-9.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_VRW_Q_SCALE_MAX="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_VRW_Q_SCALE_MAX:-4.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRBIAS_Q_SCALE_MAX="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_GYRBIAS_Q_SCALE_MAX:-4.0}"
export PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ACCBIAS_Q_SCALE_MAX="${PX4_SAFE_COMPARE_TURN_RATE_PROPAGATION_NOISE_PROBE_ACCBIAS_Q_SCALE_MAX:-2.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ENABLE="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ENABLE:-false}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_NOISE_SCALE="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_NOISE_SCALE:-false}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_MISSION="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_RTL="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_TRIGGER_MPS2="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_TRIGGER_MPS2:--0.18}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_FULL_MPS2="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_FULL_MPS2:--0.24}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MIN_HORIZONTAL_SPEED_MPS:-3.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ARW_Q_SCALE_MAX="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ARW_Q_SCALE_MAX:-1.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_VRW_Q_SCALE_MAX="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_VRW_Q_SCALE_MAX:-3.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_GYRBIAS_Q_SCALE_MAX="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_GYRBIAS_Q_SCALE_MAX:-1.0}"
export PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ACCBIAS_Q_SCALE_MAX="${PX4_SAFE_COMPARE_ACCBIAS_Z_PROPAGATION_PROBE_ACCBIAS_Q_SCALE_MAX:-6.0}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_ENABLE="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_ENABLE:-false}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_MISSION="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_RTL="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_CORE_GNSS_DIFF_H_M="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_CORE_GNSS_DIFF_H_M:-0.20}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_START_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_START_MPS:-0.03}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_FULL_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_RADIAL_FULL_MPS:-0.12}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MIN_HORIZONTAL_SPEED_MPS:-0.5}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_PERSISTENCE_UPDATES:-1}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_HOLD_UPDATES="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_HOLD_UPDATES:-0}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MIN_H_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MIN_H_MPS:-0.02}"
export PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MAX_H_MPS="${PX4_SAFE_COMPARE_GNSS_VELOCITY_OUTWARD_DAMPING_STD_MAX_H_MPS:-0.05}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_ENABLE="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_ENABLE:-false}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_MISSION="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_RTL="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_TURNING="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_TURNING:-true}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_POST_TURN="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_APPLY_POST_TURN:-true}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_CORE_GNSS_DIFF_H_M="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_CORE_GNSS_DIFF_H_M:-0.15}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_START_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_START_MPS:-0.08}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_FULL_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_RADIAL_ABS_FULL_MPS:-0.28}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_START_H_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_START_H_MPS:-0.08}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_FULL_H_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_CORE_RESIDUAL_FULL_H_MPS:-0.30}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MIN_HORIZONTAL_SPEED_MPS:-0.5}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_MAX_ABS_VERTICAL_SPEED_MPS:-1.0}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_PERSISTENCE_UPDATES:-1}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MIN_H_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MIN_H_MPS:-0.10}"
export PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MAX_H_MPS="${PX4_SAFE_COMPARE_TURN_POSTTURN_NATIVE_VELOCITY_DEWEIGHT_STD_MAX_H_MPS:-0.18}"
export PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_ENABLE="${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_ENABLE:-false}"
export PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RESIDUAL_THRESHOLD_H_M="${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RESIDUAL_THRESHOLD_H_M:-0.16}"
export PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_DX_OVER_RESIDUAL_THRESHOLD="${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_DX_OVER_RESIDUAL_THRESHOLD:-0.22}"
export PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RECENT_TURNPOST_HOLD_SEC="${PX4_SAFE_COMPARE_PHASE_ERROR_MEMORY_DEBUG_RECENT_TURNPOST_HOLD_SEC:-15.0}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ENABLE="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ENABLE:-false}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_MISSION="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_RTL="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TRIGGER_SOURCE="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TRIGGER_SOURCE:-residual_h}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MIN_H_M="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MIN_H_M:-0.08}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_NOMINAL_H_M="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_NOMINAL_H_M:-0.12}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MAX_H_M="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_FLOOR_MAX_H_M:-0.16}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_START_H_M="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_START_H_M:-0.24}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_FULL_H_M="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_RESIDUAL_FULL_H_M:-0.45}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_START_H_2D="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_START_H_2D:-5.991}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_FULL_H_2D="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_FULL_H_2D:-20.0}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_MAX_AGE_SEC="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_NIS_MAX_AGE_SEC:-2.0}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_PERSISTENCE_UPDATES:-5}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ATTACK_SEC="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ATTACK_SEC:-0.8}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_DECAY_SEC="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_DECAY_SEC:-1.2}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ARMED_CRUISE_GAIN="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_ARMED_CRUISE_GAIN:-1.0}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TURN_GAIN="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_TURN_GAIN:-1.15}"
export PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_POST_TURN_GAIN="${PX4_SAFE_COMPARE_ADAPTIVE_GNSS_POS_WEIGHT_POST_TURN_GAIN:-1.15}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SUPERVISOR_ENABLE="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SUPERVISOR_ENABLE:-false}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_MISSION="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_RTL="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_START_H_2D="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_START_H_2D:-5.991}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_FULL_H_2D="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_NIS_FULL_H_2D:-20.0}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_START_H_M="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_START_H_M:-0.20}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_FULL_H_M="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_RESIDUAL_FULL_H_M:-0.45}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_START_H_M="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_START_H_M:-0.20}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_FULL_H_M="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_CORE_GNSS_FULL_H_M:-0.45}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_START_DEG="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_START_DEG:-0.8}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_FULL_DEG="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_HEADING_RESIDUAL_FULL_DEG:-2.0}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SCORE_TRIGGER="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_SCORE_TRIGGER:-0.75}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_PERSISTENCE_UPDATES:-3}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MIN_HORIZONTAL_SPEED_MPS:-3.0}"
export PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MAX_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_HORIZONTAL_CONSISTENCY_MAX_VERTICAL_SPEED_MPS:-0.8}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ENABLE="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ENABLE:-false}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_MISSION="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_RTL="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_START="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_START:-6.0}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_FULL="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_HNIS_FULL:-20.0}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_START_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_START_H_M:-0.15}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_FULL_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_RESID_FULL_H_M:-0.35}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_LO_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_LO_H_M:-0.025}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_HI_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_POS_STD_TIGHT_HI_H_M:-0.050}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_LOW="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_LOW:-0.15}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_HIGH="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DX_RATIO_HIGH:-0.35}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_PERSISTENCE_UPDATES:-3}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ATTACK_SEC="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_ATTACK_SEC:-4.0}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DECAY_SEC="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_DECAY_SEC:-15.0}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MIN_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MIN_H_M:-0.06}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_NOMINAL_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_NOMINAL_H_M:-0.08}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MAX_H_M="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_FLOOR_MAX_H_M:-0.12}"
export PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_OFFDIAG_CORR_LIMIT="${PX4_SAFE_COMPARE_MISSION_COV_HYGIENE_OFFDIAG_CORR_LIMIT:-0.70}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_ENABLE="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_ENABLE:-false}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_MISSION="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_RTL="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_START_MPS="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_START_MPS:-3.5}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_FULL_MPS="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_HSPEED_FULL_MPS:-5.0}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_MAX_ABS_VSPEED_MPS="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_MAX_ABS_VSPEED_MPS:-0.35}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MIN_H_M="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MIN_H_M:-0.08}"
export PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MAX_H_M="${PX4_SAFE_COMPARE_MOTION_GNSS_POS_WEIGHT_STD_MAX_H_M:-0.14}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ENABLE="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ENABLE:-false}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_MISSION="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_RTL="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_START_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_START_H_M:-0.32}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_FULL_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_RESIDUAL_FULL_H_M:-0.45}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_START_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_START_H_M:-0.30}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_FULL_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_FULL_H_M:-0.55}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_SCORE_GAIN="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_CORE_SCORE_GAIN:-0.25}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MIN_HORIZONTAL_SPEED_MPS:-3.0}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_MAX_ABS_VERTICAL_SPEED_MPS:-0.35}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_PERSISTENCE_UPDATES="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_PERSISTENCE_UPDATES:-3}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_HOLD_SEC="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_HOLD_SEC:-3.0}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ATTACK_SEC="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_ATTACK_SEC:-0.5}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_DECAY_SEC="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_DECAY_SEC:-2.0}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MIN_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MIN_H_M:-0.12}"
export PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MAX_H_M="${PX4_SAFE_COMPARE_GNSS_POS_RECOVERY_WEIGHT_STD_MAX_H_M:-0.16}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_ENABLE="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_ENABLE:-false}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_STD_DEG="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_STD_DEG:-2.0}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_RESIDUAL_DEG="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_RESIDUAL_DEG:-0.15}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_RESIDUAL_DEG="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_RESIDUAL_DEG:-1.0}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MIN_HORIZONTAL_SPEED_MPS:-4.5}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_VERTICAL_SPEED_MPS:-0.35}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_GYRO_DEG_S="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_GYRO_DEG_S:-3.5}"
export PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_SOURCE_YAW_RATE_DEG_S="${PX4_SAFE_COMPARE_HEADING_CRUISE_MICRO_TRACK_MAX_SOURCE_YAW_RATE_DEG_S:-1.0}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_ENABLE="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_ENABLE:-false}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_MISSION="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_MISSION:-true}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_RTL="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_RTL:-false}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_ARMED_CRUISE="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_ARMED_CRUISE:-true}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_POST_TURN="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_POST_TURN:-true}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_TURN="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_TURN:-false}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_UPDATE="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_APPLY_UPDATE:-false}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_YAW_STD_FLOOR_DEG="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_YAW_STD_FLOOR_DEG:-1.0}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_RESIDUAL_DEG="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_RESIDUAL_DEG:-0.5}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RESIDUAL_DEG="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RESIDUAL_DEG:-2.0}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_HORIZONTAL_SPEED_MPS="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MIN_HORIZONTAL_SPEED_MPS:-3.0}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_ABS_VERTICAL_SPEED_MPS="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_ABS_VERTICAL_SPEED_MPS:-0.5}"
export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_GYRO_DEG_S="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_GYRO_DEG_S:-8.0}"
	export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_SOURCE_YAW_RATE_DEG_S="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_SOURCE_YAW_RATE_DEG_S:-3.0}"
	export PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RATE_HZ="${PX4_SAFE_COMPARE_HEADING_YAW_GAIN_HYGIENE_MAX_RATE_HZ:-5.0}"
	export PX4_SAFE_COMPARE_ENABLE_RQ_SHADOW="${PX4_SAFE_COMPARE_ENABLE_RQ_SHADOW:-false}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_NAMESPACE="${PX4_SAFE_COMPARE_RQ_SHADOW_NAMESPACE:-/rq_shadow}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_PARAM_FILE="${PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_PARAM_FILE:-${PX4_SAFE_COMPARE_KF_GINS_PARAM_FILE}}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_CORE_CONFIG_FILE="${PX4_SAFE_COMPARE_RQ_SHADOW_KF_GINS_CORE_CONFIG_FILE:-${PX4_SAFE_COMPARE_KF_GINS_CORE_CONFIG_FILE}}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_START_DELAY_SEC="${PX4_SAFE_COMPARE_RQ_SHADOW_START_DELAY_SEC:-2.0}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_GNSS_UPDATE_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_GNSS_UPDATE_DEBUG_CSV_PATH:-${RUN_DIR}/rq_shadow_gnss_update_debug.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_GNSS_NIS_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_GNSS_NIS_DEBUG_CSV_PATH:-__disabled__}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_STATE_UPDATE_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_STATE_UPDATE_DEBUG_CSV_PATH:-${RUN_DIR}/rq_shadow_state_update_debug.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_STATE_PUBLISH_DEBUG_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_STATE_PUBLISH_DEBUG_CSV_PATH:-${RUN_DIR}/rq_shadow_state_publish_debug.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_ENABLE="${PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_ENABLE:-true}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_CSV_PATH:-${RUN_DIR}/rq_shadow_ekf_iekf_pairs.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_RATE_HZ="${PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_RATE_HZ:-${PX4_SAFE_PAIR_LOGGER_RATE_HZ:-10}}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_SYNC_TOLERANCE_MS="${PX4_SAFE_COMPARE_RQ_SHADOW_PAIR_LOGGER_SYNC_TOLERANCE_MS:-${PX4_SAFE_PAIR_LOGGER_SYNC_TOLERANCE_MS:-50}}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_TOPIC="${PX4_SAFE_COMPARE_SHADOW_RESTORE_TOPIC:-/kf_gins/main_to_shadow_snapshot}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_MAIN_PUBLISH_ENABLE="${PX4_SAFE_COMPARE_SHADOW_RESTORE_MAIN_PUBLISH_ENABLE:-false}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_AFTER_CORE_SEC="${PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_AFTER_CORE_SEC:-40.0}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_ONCE="${PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_ONCE:-true}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_PERIOD_SEC="${PX4_SAFE_COMPARE_SHADOW_RESTORE_PUBLISH_PERIOD_SEC:-0.0}"
	export PX4_SAFE_COMPARE_SHADOW_RESTORE_MAIN_EVENT_CSV_PATH="${PX4_SAFE_COMPARE_SHADOW_RESTORE_MAIN_EVENT_CSV_PATH:-${RUN_DIR}/main_shadow_restore_events.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_SUBSCRIBE_ENABLE="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_SUBSCRIBE_ENABLE:-false}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_EVENT_CSV_PATH="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_EVENT_CSV_PATH:-${RUN_DIR}/rq_shadow_restore_events.csv}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_MAX_AGE_SEC="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_MAX_AGE_SEC:-0.75}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_COVARIANCE_INFLATION_FACTOR="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_COVARIANCE_INFLATION_FACTOR:-1.0}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_REQUIRE_CORE_INITIALIZED="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_REQUIRE_CORE_INITIALIZED:-true}"
	export PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_CLEAR_PATH_ON_APPLY="${PX4_SAFE_COMPARE_RQ_SHADOW_RESTORE_CLEAR_PATH_ON_APPLY:-true}"
	export PX4_SAFE_START_PAIR_LOGGER="${PX4_SAFE_START_PAIR_LOGGER:-0}"
export PX4_SAFE_PAIR_LOGGER_CSV_PATH="${PX4_SAFE_PAIR_LOGGER_CSV_PATH:-${RUN_DIR}/ekf_iekf_pairs.csv}"
export PX4_SAFE_PAIR_LOGGER_RATE_HZ="${PX4_SAFE_PAIR_LOGGER_RATE_HZ:-10}"
export PX4_SAFE_PAIR_LOGGER_SYNC_TOLERANCE_MS="${PX4_SAFE_PAIR_LOGGER_SYNC_TOLERANCE_MS:-50}"
export PX4_SAFE_GPS_PROBE_CSV_PATH="${PX4_SAFE_GPS_PROBE_CSV_PATH:-${RUN_DIR}/gps_vs_pose.csv}"
export PX4_SAFE_GPS_PROBE_SECOND_CSV_PATH="${PX4_SAFE_GPS_PROBE_SECOND_CSV_PATH:-${RUN_DIR}/gps_vs_second_pose.csv}"
export PX4_SAFE_GPS_PROBE_PAIR_AFTER_NEWER_POSE="${PX4_SAFE_GPS_PROBE_PAIR_AFTER_NEWER_POSE:-true}"
export PX4_SAFE_GPS_PROBE_MAX_PAIR_WAIT_SEC="${PX4_SAFE_GPS_PROBE_MAX_PAIR_WAIT_SEC:-0.25}"

case "${CMD}" in
  start)
    mkdir -p "${RUN_DIR}"
    printf '[manual-postflight] run_dir=%s\n' "${RUN_DIR}"
    printf '[manual-postflight] keep the session idle for 30-60s after landing/disarm before stop\n'
    exec "${BRINGUP_SCRIPT}" start "${RUN_DIR}"
    ;;
  status)
    exec "${BRINGUP_SCRIPT}" status "${RUN_DIR}"
    ;;
  stop)
    exec "${BRINGUP_SCRIPT}" stop "${RUN_DIR}"
    ;;
  summary)
    summarize_run "${RUN_DIR}"
    ;;
  show-env)
    show_env
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
